baseurl = "https://voiceartist.github.io/"
languageCode = "en-us"
title = "Dan Long | Voice Actor"
theme = "hugo-strata-theme"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
publishDir = ".."

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Dan Long"
	description = "Dan Long | Voice Actor"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = true

	# Add custom assets with their paths relative to the static folder
	#custom_js   = []
	#custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**I'm Dan Long**, a super awesome<br> Voice Actor based out of San Francisco."
		# The icons will be shown if you enter your username
		twitter = "danlongvo"
		github = "fumitol"
		gitlab = ""
		#dribbble = ""
		#facebook = ""
		#googleplus = ""
		#flickr = ""
		#linkedin = ""

		copyright = [
			"&copy; Dan Long",
			"I ❤️ you",
		]


	[params.about]
		hide  = false
		title = "About **Dan Long**"
		content = "Accumsan orci faucibus id eu lorem semper. Eu ac iaculis ac nunc nisi lorem vulputate lorem neque cubilia ac in adipiscing in curae lobortis tortor primis integer massa adipiscing id nisi accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque cubilia."


	[params.audio]
		hide  = false
		title = "Hey Listen"
        
		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.audio.gallery]]
			audio = "mushroom.mp3"
			thumb = "audio/mushroom.mp3"
			title = "Commercials"
			description = ""

	[params.recentposts]
		hide  = true
		title = "Recent blog posts"

	[params.contact]
		hide  = true
		title = "Get In Touch"
		content = "You may be asking, '**Dan**, how do I get in touch with you so I can hire you for a project?' Sadly, I am currently on haitus, but hope to be back soon to help you with your Voice Over needs. Once that happens, there will be a pretty form down below for you to fill out."

		# This can be exact coordinates or a searchable address in google maps
		gmaps_address = "39.7889055,-120.5443524"
		address = [
			"1234 Somewhere Rd.",
			"San Francisco, CA 94103",
			"United States"
		]
		#phone = "000-000-0000"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "hello@example.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
#[[menu.main]]
#	name = "Home"
#	url  = "/"
#	weight = 10

#[[menu.main]]
#	name = "Blog"
#	url  = "post/"
#	weight = 0
